Update repository.md
Should probably be something like this. however:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py:286, in hf_raise_for_status(response, endpoint_name)
    285 try:
--> 286     response.raise_for_status()
    287 except HTTPError as e:

File ~/.local/lib/python3.10/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/datasets/mylesdyson/speecht5-tts-demo/branch/handle-dog-speaker

The above exception was the direct cause of the following exception:

HfHubHTTPError                            Traceback (most recent call last)
Cell In[33], line 1
----> 1 create_branch("mylesdyson/speecht5-tts-demo", repo_type="dataset", revision="v0.1-release", branch="handle-dog-speaker", token=HF_TOKEN)

File ~/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:118, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    115 if check_use_auth_token:
    116     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 118 return fn(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py:5416, in HfApi.create_branch(self, repo_id, branch, revision, token, repo_type, exist_ok)
   5414 response = get_session().post(url=branch_url, headers=headers, json=payload)
   5415 try:
-> 5416     hf_raise_for_status(response)
   5417 except HfHubHTTPError as e:
   5418     if not (e.response.status_code == 409 and exist_ok):

File ~/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py:333, in hf_raise_for_status(response, endpoint_name)
    329     raise BadRequestError(message, response=response) from e
    331 # Convert `HTTPError` into a `HfHubHTTPError` to display request information
    332 # as well (request id and/or server error message)
--> 333 raise HfHubHTTPError(str(e), response=response) from e

HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/datasets/mylesdyson/speecht5-tts-demo/branch/handle-dog-speaker (Request ID: Root=1-65be83fd-3135f8d408317cb35de19e7b;3cbbfeee-a0dc-4be7-856b-0cf2282b0999)

Internal Error - We're working hard to fix this as soon as possible!