Update typer dependency version in setup.py
Hello!

## Pull Request overview
* Add a minimum version for `typer`

## Details
As shown in this documentation page (https://typer.tiangolo.com/tutorial/commands/help/#suggest-commands), the `suggest_commands` parameter was only added in typer 0.20.0. It's being used by hf_hub, so we must ensure that typer gets updated (or we only add `suggest_commands=False` if typer is newer than 0.20.0, that would also be fine). 

Either way, upgrading `huggingace_hub` didn't push my typer, which was still at `0.18.0`, resulting in:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tom\.conda\envs\sentence-transformers\Scripts\hf.exe\__main__.py", line 4, in <module>
  File "C:\Users\tom\.conda\envs\sentence-transformers\Lib\site-packages\huggingface_hub\cli\hf.py", line 24, in <module>
    from huggingface_hub.cli.auth import auth_cli
  File "C:\Users\tom\.conda\envs\sentence-transformers\Lib\site-packages\huggingface_hub\cli\auth.py", line 49, in <module>
    auth_cli = typer_factory(help="Manage authentication (login, logout, etc.).")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\.conda\envs\sentence-transformers\Lib\site-packages\huggingface_hub\cli\_cli_utils.py", line 639, in typer_factory
    return HFCliApp(
           ^^^^^^^^^
TypeError: Typer.__init__() got an unexpected keyword argument 'suggest_commands'
```
With any `hf` CLI command. Adding a minimum version would be safer.

- Tom Aarsen