Update repository.md
create_branch() no longer accepts "tag_message" as well.

https://huggingface.co/docs/huggingface_hub/v0.20.3/en/package_reference/hf_api#huggingface_hub.HfApi.create_branch


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 1
----> 1 create_branch(
      2     "mylesdyson/speecht5-tts-demo",
      3     repo_type="dataset",
      4     revision="v0.1-release",
      5     tag_message="Bump release version.",
      6     token=HF_TOKEN
      7 )

File ~/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:118, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    115 if check_use_auth_token:
    116     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 118 return fn(*args, **kwargs)

TypeError: HfApi.create_branch() got an unexpected keyword argument 'tag_message'